### ISSUE TITLE
Redirect 301/308 problem

### ISSUE THREAD

**Issue by Glajik** [Glajik/BTC-Invoice-Bot#36]
All POST requests redirected with 301, then 308 and changed to GET

**Comment by Glajik** [comment]
Looks like it's because of that redundant settings in app.yaml:
```YAML
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
```
